name: Simulate a failing job and send a notification to Discord

on: {}
  # push:
  #   branches:
  #     - test

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simulate a failing job
        run: |
          echo "This job will fail"
          exit 1

      - uses: actions/setup-ruby@v1
      - name: Send Webhook Notification
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_TOKEN_DOCKER }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          git clone https://github.com/elendil7/github-actions-discord-webhook webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash