name: Redeploy to Oracle on Push to Main

# On push to main branch of repository...
on:
  push:
    branches:
      - main
  
jobs:
  redeploy:
    # Run on Ubuntu (Oracle server is Ubuntu / Linux)
    runs-on: ubuntu-latest

    # Pull changes from GitHub repo to Oracle server, and set variable to "true" if changes are detected
    steps:
      # Checkout code from GitHub repo
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      # Check for changes in /src folder or the config.ts file, and store result in variable
      - name: Check for changes in /src folder or the config.ts file
        id: changes
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD) =~ ^src/|^\config\.ts$ ]]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      # Exit workflow if no changes detected
      - name: Exit workflow if no changes
        if: ${{ steps.changes.outputs.changed == 'false' }}
        run: exit 0

      # Connect to Oracle server via SSH and execute deploy script there
      - name: Connect to Oracle server via SSH and execute commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ORACLE_SERVER_HOST }}
          username: ${{ secrets.ORACLE_SERVER_USERNAME }}
          key: ${{ secrets.ORACLE_SERVER_PRIVATE_KEY }}
          port: 22
          script: ssh ${{ secrets.ORACLE_SERVER_USERNAME }}@${{ secrets.ORACLE_SERVER_HOST }} 'bash -s' < deploy/deploy.sh
          command_timeout: 20m
          
      # Send message to Discord channel to confirm deployment
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DOCKER_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DOCKER_WEBHOOK_TOKEN }}
          message: |
            **Deployment successful**
            *Docker image deployed to Oracle server.*

            - Commit: `${{ github.sha }}`
            - Branch: `${{ github.ref }}`
            - Event: `${{ github.event_name }}`
            - 
          color: 43520
          avatar_url: https://images-ext-1.discordapp.net/external/fdSG9WottHrn1cVRMO0RQC5t0hvwHVKtgYpTJWJjk6s/https/cdn-icons-png.flaticon.com/512/190/190411.png